### ISSUE TITLE
Assignment algorithm

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx/Chemist#11]
Given a molecular system we need an algorithm that  can determine the spatial symmetry of that system.  Ideally, this algorithm should:

- [ ] Identify point group for non-periodic systems using class in #10 
- [ ] Identify space group for periodic systems using class in #9 
- [ ] Identify the symmetry elements of the group using class in #12
